-- AlterTable
ALTER TABLE `user` ADD COLUMN `banReason` TEXT NULL,
    ADD COLUMN `bannedAt` DATETIME(3) NULL,
    ADD COLUMN `flagReason` TEXT NULL,
    ADD COLUMN `flaggedAt` DATETIME(3) NULL,
    ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `isBanned` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isFlagged` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isMuted` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isRestricted` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isSuspended` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isWarned` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `lastActivityAt` DATETIME(3) NULL,
    ADD COLUMN `lastLoginAt` DATETIME(3) NULL,
    ADD COLUMN `moderatedBy` VARCHAR(191) NULL,
    ADD COLUMN `moderationNotes` TEXT NULL,
    ADD COLUMN `muteEndsAt` DATETIME(3) NULL,
    ADD COLUMN `muteReason` TEXT NULL,
    ADD COLUMN `mutedAt` DATETIME(3) NULL,
    ADD COLUMN `reportsMade` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `reportsReceived` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `restrictedAt` DATETIME(3) NULL,
    ADD COLUMN `restrictionEndsAt` DATETIME(3) NULL,
    ADD COLUMN `restrictionReason` TEXT NULL,
    ADD COLUMN `suspendedAt` DATETIME(3) NULL,
    ADD COLUMN `suspensionCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `suspensionEndsAt` DATETIME(3) NULL,
    ADD COLUMN `suspensionReason` TEXT NULL,
    ADD COLUMN `warnedAt` DATETIME(3) NULL,
    ADD COLUMN `warningCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `warningReason` TEXT NULL;
